# Generated by Django 3.0.5 on 2020-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201220_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='name',
            field=models.CharField(default='Tanishq', max_length=20),
            preserve_default=False,
        ),
    ]
